# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-06-07 02:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Course Name')),
                ('desc', models.CharField(max_length=500, verbose_name='Course Description')),
                ('detail', models.CharField(max_length=100, verbose_name='Course Detail')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10, verbose_name='Course Difficulty')),
                ('course_duration', models.IntegerField(default=0, verbose_name='Course Duration')),
                ('student_count', models.IntegerField(default=0, verbose_name='Student Count')),
                ('fav_count', models.IntegerField(default=0, verbose_name='Favourite Count')),
                ('click_count', models.IntegerField(default=0, verbose_name='Click Count')),
                ('image', models.ImageField(default='image/courses/course/default.png', max_length=200, upload_to='image/courses/course/%Y/%m', verbose_name='Course Image')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Course Created Time')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Lesson Name')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Lesson Created Time')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Course Name')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Resource Name')),
                ('download', models.FileField(default='file/courses/res/default.md', upload_to='file/courses/res/%Y/%m', verbose_name='Resource Name')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Resource Created Time')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Course Name')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Video Name')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Video Created Time')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='Lesson Name')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
