# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-07-04 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190606_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileverification',
            name='verify_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Verification Time'),
        ),
    ]
