# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-06-30 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_courseorg_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='course_count',
            field=models.IntegerField(default=0, verbose_name='Course Count'),
        ),
        migrations.AddField(
            model_name='courseorg',
            name='student_count',
            field=models.IntegerField(default=0, verbose_name='Student Count'),
        ),
    ]
