# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-07-04 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20190630_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='avatar',
            field=models.ImageField(null=True, upload_to='organizations/instructor/%Y/%m', verbose_name='Avatar'),
        ),
    ]
