# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-06-07 02:23
from __future__ import unicode_literals

import datetime
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(max_length=30, verbose_name='Nick Name')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10, verbose_name='Sex')),
                ('address', models.CharField(default='', max_length=100, verbose_name='Address')),
                ('mobile', models.CharField(blank=True, max_length=10, null=True, verbose_name='Mobile Number')),
                ('image', models.ImageField(default='image/users/profile/default.png', upload_to='image/users/profile/%Y/%m', verbose_name='Profile Picture')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User Information',
                'verbose_name_plural': 'User Information',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Banner Title')),
                ('image', models.ImageField(default='image/users/banner/default.png', upload_to='image/users/banner/%Y/%m', verbose_name='Banner Picture')),
                ('url', models.URLField(verbose_name='Banner URL')),
                ('idx', models.IntegerField(default=100, verbose_name='Index')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Banner Creation Time')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
            },
        ),
        migrations.CreateModel(
            name='UserProfileVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='User Profile Verification Code')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('type', models.CharField(choices=[('register', 'Register'), ('reset', 'Reset Password')], max_length=20, verbose_name='Verification Type')),
                ('verify_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Verification Time')),
            ],
            options={
                'verbose_name': 'User Profile Verification',
                'verbose_name_plural': 'User Profile Verification',
            },
        ),
    ]
