# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-06-07 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelOptions(
            name='userprofileverification',
            options={'verbose_name': 'User Profile Verification', 'verbose_name_plural': 'User Profile Verifications'},
        ),
    ]
