# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-07-07 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='', max_length=100, verbose_name='Course Category'),
        ),
    ]
