# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-07-07 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_instructor_avatar'),
        ('courses', '0003_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Instructor', verbose_name='Instructor'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_duration',
            field=models.IntegerField(default=0, verbose_name='Video Duration'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.CharField(default='', max_length=300, verbose_name='Video URL'),
        ),
    ]
