# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-07-20 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20190707_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='on_sale',
            field=models.BooleanField(default=False, verbose_name='On Sale'),
        ),
    ]
