# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-07-24 04:03
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_on_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOnSale',
            fields=[
            ],
            options={
                'verbose_name': 'On-sale Course',
                'proxy': True,
                'verbose_name_plural': 'On-sale Courses',
            },
            bases=('courses.course',),
        ),
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='Course Detail'),
        ),
    ]
